DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (

    id SERIAL PRIMARY KEY,
    firstname VARCHAR(60) NOT NULL,
    lastname VARCHAR(60) NOT NULL,
    email VARCHAR(60) NOT NULL,
    password VARCHAR(255) NOT NULL
);